CREATE DATABASE;

USE GameVault;

CREATE TABLE IF NOT EXISTS usuario (
  USU_COD INT AUTO_INCREMENT PRIMARY KEY,
  USU_NOME VARCHAR(50) NOT NULL UNIQUE,
  USU_EMAIL VARCHAR(100) NOT NULL UNIQUE,
  USU_SENHA VARCHAR(255) NOT NULL
);